# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the firebase-deploy orb
  firebase-deploy: azdevs/firebase-deploy@1.0.0
# Create jobs for workflows
jobs:
  build:
    working_directory: ~/the-love-for-nature
    docker:
      - image: "circleci/node:lts"
    steps:
      - checkout
      - restore_cache:
          key: 'v1-package-{{ checksum "~/the-love-for-nature/functions/package.json" }}'
      - run:
          name: "Install Function Dependencies"
          command: |
            cd functions
            npm install
      - save_cache:
          paths:
            - "~/the-love-for-nature/functions/node_modules"
          key: 'v1-package-{{ checksum "~/the-love-for-nature/functions/package.json" }}'
      - persist_to_workspace:
          root: ~/the-love-for-nature
          paths:
            - experience
            - functions
            - .firebaserc
            - firebase.json
            - datbaserules.json
  deploy:
    docker:
      - image: "circleci/node:lts"
    steps:
      - attach_workspace:
          at: ~/the-love-for-nature
      - firebase-deploy/deploy:
          token: $FIREBASE_DEPLOY_TOKEN

# Orchestrate or schedule a set of jobs
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
